# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3723b45caa5ff92e70a98d2a9910cd137de3220fdfb3c71bf5f48adcaa50d24cdaefa21b8a0c22672b09fddf3985d8ef48f99b58632d091fb6951b3f035c8ad

test:
  secret_key_base: d186f7c402e2051d37f769055fc421b7f4795c6958921f076982e4d2054d8fe9ad878761b11fb766490d5fee13601035438cb4cadb84e1e38c143f81880f5721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
